<% header(name + ' 1.0.2 Release Notes') %>

<p><% name %> version 1.0.2 released on 06/07/09</p>

<a id="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>The file extensions of the files that shall be parsed as Kid templates
  can now be configured using the setting <code>ExtensionsForKid</code>.
  By default (as before), only files with the extension <code>.kid</code>
  are regarded as Kid templates.</li>
</ul>

<% footer() %>
