<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
  <li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>Do not put timed actions, i.e. tasks to be run once, on the "on demand"
  list after they have finished, because this will prevent releasing their
  resources when they have done their job. Manage an <code>onDemand</code>
  state on the <code>TaskHandler</code> separately. (Reported as bug #101
  with fix by Ben Parker.)</li>
</ul>

<% footer() %>
