<% header(name + " User's Guide") %>

<p class="right"><% name %> version <% versionString %></p>


<a id="Synopsis"></a><h2>Synopsis</h2>

<p>TaskKit provides a framework for the scheduling and management of tasks which can be triggered periodically or at specific times. Tasks can also be forced to execute immediately, set on hold or rescheduled with a different period (even dynamically).</p>


<a id="Feedback"></a><h2>Feedback</h2>

<p>You can e-mail <a href="mailto:webware-discuss@lists.sourceforge.net">webware-discuss@lists.sourceforge.net</a> to give feedback, discuss features and get help using TaskKit.</p>


<a id="Introduction"></a><h2>Introduction</h2>

<a id="Overview"></a><h3>Overview</h3>

<p>Task Kit does not have a real User's Guide yet. However, there is a <a href="QuickStart.html">Quick Start</a> article and there are docstrings in the source code. Also, if you search WebKit for "task" you will find a real world use of this kit.</p>


<a id="KnownBugs"></a><h2>Known Bugs</h2>

<p>Known bugs and future work in general, are documented in <a href="TODO.text">TO DO</a>.</p>


<a id="Credit"></a><h2>Credit</h2>

<p>Authors: Tom Schwaller, Jay Love</p>
<p>Based on code from the Ganymede Directory Management System written by Jonathan Abbey.</p>

<% footer() %>
