<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a id="Introduction"></a><h2>Introduction</h2>
<ul>
  <li>...</li>
</ul>

<a id="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a id="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>...</li>
</ul>

<a id="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a id="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a id="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>...</li>
</ul>

<a id="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>Fixed problem when executing SQL without <code>clausesArgs</code>
  in SQLiteObjectStore (as suggested by Nico Latzer).</li>
  <li>Fixed bug in <code>MiddleObject.htObjectsInList</code>
  (as suggested by Nico Latzer).</li>
  <li>Fixed bug in <code>MiddleObject.htObjectsInList</code>
  (as suggested by Nico Latzer).</li>
  <li>Fix problem when setting cookies in StorePage (as suggested by
  Nico Latzer).</li>
</ul>

<% footer() %>
