<% header(name + ' 1.0 Release Notes') %>

<p><% name %> version 1.0 released on 11/29/08</p>

<a id="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>You can now use the sha-1 secure hash algorithm instead of md5 with
  <code>Funcs.uniqueId()</code> by setting <code>sha=True</code>.</li>
</ul>

<a id="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>You can now use the sha-1 secure hash algorithm instead of md5 with
  <code>Funcs.uniqueId()</code> by setting <code>sha=True</code>.</li>
  <li>Made <code>PickleRPC</code> use the newer httplib interface
  available since Python 2.0.</li>
</ul>

<a id="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>Fixed a bug in <code>PickleRPC.Server</code>.</li>
</ul>

<% footer() %>
