<% header(name + ' 1.1 Release Notes') %>

<p><% name %> version 1.1 released on 08/03/11</p>

<a id="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>The parser has been optimized and checks for invalid attributes now.</li>
  <li>Files included with the include directive are now watched by the import
  manager so the app server can automatically reload when they are changed.</li>
</ul>

<% footer() %>
