<% header(name + ' 1.0.2 Release Notes') %>

<p><% name %> version 1.0.2 released on 06/07/09</p>

<a id="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>The file extensions of the files that shall be parsed as PSP
  can now be configured using the setting <code>ExtensionsForPSP</code>
  (suggested by Tobias Franz). By default (as before), only files with
  the extension <code>.psp</code> are regarded as PSP files.</li>
  <li>You can now use an arbitrary encoding for your PSP files if you
  specify the encoding in the <code>PSPFileEncoding</code> setting.</li>
</ul>

<a id="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>Empty PSP tags are now silently ignored.</li>
</ul>

<a id="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>When using the psp-handler of mod_webkit, request methods like
  <code>servletPath()</code> and others returned values which were different
  from what you get when using the ordinary webkit-handler. This could
  cause various problems, for instance because the default cookie path
  is set to the servlet path (reported by Fionn Behrens). To avoid such
  problems, requests made via the psp-handler now will look much more
  similar to a request made via the ordinary webkit-handler.</li>
</ul>

<% footer() %>
