<% header(name + ' 1.0 Release Notes') %>

<p><% name %> version 1.0 released on 11/29/08</p>

<a id="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>Output is now nicer and fully HTML compliant.</li>
  <li>A couple of minor improvements and code clean-up.</li>
</ul>

<a id="Security"></a><h2>Security</h2>
<ul>
  <li>Access to the admin scripts is now restricted to the local host.
  A new setting <code>AdminRemoteAddr</code> allows adding
  more remote addresses for administration.</li>
  <li>The view scripts do not allow changing the path any more.</li>
</ul>

<a id="MinorChanges"></a><h2>Minor Changes</h2>
<ul>
  <li>The default config file has been renamed to
  <span class="filename">CGIWrapper.config</span>.</li>
  <li>The default <code>ScriptsHomeDir</code> has been changed to
  <span class="filename">Examples</span>.</li>
</ul>

<% footer() %>
