<% header(name + ' 1.1.3 Release Notes') %>

<p><% name %> version 1.1.3 released on 11/21/16</p>

<a name="Introduction"></a><h2>Introduction</h2>
<ul>
  <li>...</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>You can now specify attributes to be set on the root HTML element of
  the <code>Page</code> servlet. By default, the document language will be
  set to English using the <code>lang</code> Attribute.</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>Fixed a race condition in the <code>SessionDynamicStore</code>
  (thanks to Ben Parker).</li>
</ul>

<% footer() %>
