<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a id="Introduction"></a><h2>Introduction</h2>
<ul>
  <li>...</li>
</ul>

<a id="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a id="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>You can now specify attributes to be set on the root HTML element of
  the <code>Page</code> servlet. By default, the document language will be
  set to English using the <code>lang</code> Attribute.</li>
</ul>

<a id="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a id="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a id="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>...</li>
</ul>

<a id="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>Fixed a race condition in the <code>SessionDynamicStore</code>
  (thanks to Ben Parker).</li>
</ul>

<% footer() %>
