<% header(name + ' 1.1 Release Notes') %>

<p><% name %> version 1.1 released on 08/03/11</p>

<a id="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>To conform with Webwares naming conventions and because it now deviates
  pretty much from the original <code>cgitb</code>, renamed
  <code>WebUtils.cgitb</code> to <code>WebUtils.CGITraceback</code>.</li>
</ul>

<a id="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>The modified <code>FieldStorage</code> class did not work as before with
  Python 2.6 and newer. These Python versions already add query string parameters
  to the fields passed via POST, but differently to how we did this before.
  POST parameters used to completely override query string parameters, the values
  were not appended to possibly existing values in the query string. In order
  to stay compatible and because it seems to be more reasonable, we restored the
  old behavior even for newer versions of Python (thanks to Fionn Behrens for
  bringing this up).</li>
</ul>

<a id="Deprecations"></a><h2>Deprecations</h2>
<ul>
  <li>The methods and objects which have been marked as deprecated
  in version 1.0 and modules that are now available in the standard library
  have been removed in Webware for Python 1.1, particularly
  <code>Cookie</code>, <code>cgitb</code> and <code>WebFuncs</code>.</li>
</ul>

<% footer() %>
