<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a id="Security"></a><h2>Security</h2>
<ul>
  <li>The modified <code>FieldStorage</code> class did not work any more with
  versions of Python 2.7 in which vendors have backported a security fix from
  Python 3 using an additional <code>separator</code> parameter. This parameter
  is now properly recognized and handled by Webware as well.</li>
</ul>

<% footer() %>
