<% header(name + ' Documentation', 'titlebar', 'DocIndex.css') %>

<table class="doc">
<tr>
  <td class="InfoLabel">Name:</td>
  <td class="InfoValue"><b><% name %></b></td>
  <td class="InfoLabel top">Summary:</td>
</tr><tr>
  <td class="InfoLabel">Version:</td>
  <td class="InfoValue"><% versionString %></td>
  <td rowspan="4" class="InfoSummary top"><% synopsis %></td>
</tr>
<tr>
  <td class="InfoLabel">Status:</td>
  <td class="InfoValue"><% status %></td>
</tr>
<tr>
  <td class="InfoLabel">Py Ver:</td>
  <td class="InfoValue"><% requiredPyVersionString %></td>
</tr>
<tr>
  <td class="InfoLabel">Webware:</td>
  <td class="InfoValue"><% webwareVersionString %></td>
</tr>
</table>

<p>&nbsp;</p>

<table class="doc">
<tr>
  <td class="InfoLabel">Manuals:</td>
  <td class="InfoLabel">Source:</td>
  <td class="InfoLabel">Release Notes:</td>
</tr><tr>
  <td class="InfoValue top"><% htDocs %></td>
  <td class="InfoValue top">
    <p><a href="Source/ClassHierarchy.html" class="DocLink">Class hierarchy</a></p>
    <p><a href="Source/ClassList.html" class="DocLink">Class list</a></p>
    <p><a href="Source/FileList.html" class="DocLink">File list</a></p>
  </td>
    <td class="InfoValue top"><% htReleaseNotes %></td>
</tr>
</table>

<% footer() %>
