<% header(name + ' 1.0.2 Release Notes') %>

<p><% name %> version 1.0.2 released on 06/07/09</p>

<ul>
  <li>This is the second bugfix release for Webware for Python release 1.0,
  mainly fixing some problems and shortcomings of the PSP plug-in.
  See the WebKit and PSP release notes for details.</li>
  <li>This bugfix release can be used with Python versions 2.0 to 2.6.</li>
</ul>

<% footer() %>
