<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Introduction"></a><h2>Introduction</h2>
<p>...</p>

<p>Note that Webware for Python has a new homepage at
<a href="https://cito.github.io/w4py/">cito.github.io/w4py/</a>
and the old Wiki has been closed and archived at
<a href="https://cito.github.io/w4py-olde-wiki/">cito.github.io/w4py-olde-wiki/</a>.
Development has moved from the old SVN repository which has been archived
at <a href="https://github.com/Cito/w4py-olde-docs/">github.com/Cito/w4py-olde-docs/</a>
to a new GitHub repository at <a href="https://github.com/Cito/w4py">github.com/Cito/w4py</a>.</p>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>...</li>
</ul>

<% footer() %>
