<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a id="Changes"></a><h2>Changes</h2>
<ul>
  <li>Webware 1.2.4 is a patch release with one minor improvement described
  in the WebUtils release note. You may need this patch if you use a Python 2
  version with vendor-supplied security patches.</li>
</ul>

<% footer() %>
