<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<li>Webware 1.2.3 is a bugfix release with minor improvements and fixes
listed in the WebKit, MiddleKit, and MiscUtils release notes. We also
updated the documentation with the current status and a link to the
follow-up project for Python 3, and fixed some spelling errors.</li>

<% footer() %>
