<% header(name + ' 1.0.1 Release Notes') %>

<p><% name %> version 1.0.1 released on 02/06/09</p>

<ul>
  <li>This is the first bugfix release for Webware for Python release 1.0,
  mainly fixing a problem that could appear when communicating with the
  threaded application server over a network connection.
  See the WebKit release notes for details.</li>
  <li>This bugfix release can be used with Python versions 2.0 to 2.6.</li>
</ul>

<% footer() %>
