<% header(name + ' 1.0 Release Notes') %>

<p><% name %> version 1.0 released on 11/29/08</p>

<ul>
  <li>This is the historic Webware for Python release 1.0. It runs with
  all Python versions from 2.0 to 2.6. Bugfix releases will have version
  numbers 1.0.x and remain compatible with all these Python versions.
  Future development will start with Webware for Python version 1.1 and
  require more modern Python versions.</li>
  <li>A lot of bugs have been fixed, and a few small improvements and changes
  have been made since the last release. See the release notes for WebKit,
  MiddleKit, TaskKit and CGIWrapper for details.</li>
</ul>

<% footer() %>
