<% header(name + ' ' + versionString + ' Release Notes') %>

<p><% name %> version <% versionString %> released on <% releaseDate %></p>

<a name="Changes"></a><h2>Changes</h2>
<ul>
  <li>The main change in the Webware 1.2 branch is that it now requires
  at least Python version 2.6 or 2.7, while the Webware 1.1 branch still
  supports Python 2.4 and 2.5. The code has become a bit cleaner and leaner
  again, and by using more modern Python idioms also a bit faster. We do not
  yet support Python 3, but these changes give us a good starting point for
  further modernization of Webware for Python.</li>
</ul>

<a name="MajorChanges"></a><h2>Major Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="NewFeatures"></a><h2>New Features</h2>
<ul>
  <li>...</li>
</ul>

<a name="Improvements"></a><h2>Improvements and Refinements</h2>
<ul>
  <li>...</li>
</ul>

<a name="Security"></a><h2>Security</h2>
<ul>
  <li>...</li>
</ul>

<a name="MinorChanges"></a><h2>Minor API Changes</h2>
<ul>
  <li>...</li>
</ul>

<a name="Bugfixes"></a><h2>Bugfixes</h2>
<ul>
  <li>...</li>
</ul>

<% footer() %>
