<% header(name + ' 1.1.2 Release Notes') %>

<p><% name %> version 1.1.2 released on 08/12/16</p>

<a id="Changes"></a><h2>Changes</h2>
<ul>
  <li>Webware 1.1.2 is a bugfix release with several small improvements and
  fixes over the Webware 1.1.1 release, listed in the WebKit release notes.</li>
  <li>Note that Webware for Python has a new homepage at
  <a href="https://cito.github.io/w4py/">cito.github.io/w4py/</a>
  and the old Wiki has been closed and archived at
  <a href="https://cito.github.io/w4py-olde-wiki/">cito.github.io/w4py-olde-wiki/</a>.
  Development has moved from the old SVN repository, which has been archived
  at <a href="https://github.com/Cito/w4py-olde-docs/">github.com/Cito/w4py-olde-docs/</a>,
  to a new GitHub repository at <a href="https://github.com/Cito/w4py">github.com/Cito/w4py</a>.</li>
</ul>

<% footer() %>
