<% header(name + ' 1.2.3 Release Notes') %>

<p><% name %> version 1.2.3 released on 01/09/20</p>

<a id="Changes"></a><h2>Changes</h2>
<ul>
  <li>Webware 1.2.3 is a bugfix release with minor improvements and fixes
  listed in the WebKit, MiddleKit, and MiscUtils release notes. We also
  updated the documentation with the current status and a link to the
  follow-up project for Python 3, and fixed some spelling errors.</li>
</ul>

<% footer() %>
